# Generated by Django 4.2.2 on 2023-06-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('jobid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('skils', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
    ]
