# Generated by Django 4.2.2 on 2023-06-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jobs',
        ),
    ]
